import Link from "next/link";

const projects = [
  { number:"01", kicker:"PLATAFORMA DE CONTEÚDO", name:"NEXUS IA", lead:"NEXUS", italic:"IA", description:"Uma operação modular que transforma a estratégia de um canal em conteúdo, mídia, narração, vídeo e publicação — com pipeline, aprovações e agenda em um único produto.", tags:["Next.js","TypeScript","FFmpeg","IA"], variant:"nexus", label:"PROJETO PRIVADO" },
  { number:"02", kicker:"OPERAÇÃO EMPRESARIAL", name:"TRAGIAL ONE", lead:"TRAGIAL", italic:"ONE", description:"Sistema interno para registro de ponto e automação de setores. Centraliza rotinas, padroniza processos e transforma atividades operacionais em fluxos rastreáveis.", tags:["Automação","Operações","Dashboards"], variant:"tragial", label:"SISTEMA INTERNO" },
  { number:"03", kicker:"GAME PLATFORM ENGINEERING", name:"VORTEX PLATFORM", lead:"VORTEX", italic:"PLATFORM", description:"Um runtime que transforma Minecraft em plataforma: proxy Velocity, backend Minestom embarcado, experiências em Lua, sharding de lobby, studio e persistência de mundos.", tags:["Java","Velocity","Minestom","Lua"], variant:"vortex", label:"VER REPOSITÓRIO", href:"https://github.com/AssisCabron/VortexProxy" },
  { number:"04", kicker:"INFRAESTRUTURA EM TEMPO REAL", name:"REX ECOSYSTEM", lead:"REX", italic:"ECOSYSTEM", description:"Painel e daemon para gerenciar servidores, arquivos, bancos, usuários e recursos em tempo real — com Docker, WebSockets, segurança, balanceamento e observabilidade.", tags:["Next.js","Node.js","Docker","Socket.io"], variant:"rex", label:"REXPANEL + DAEMON", href:"https://github.com/AssisCabron/RexPanel" },
  { number:"05", kicker:"LICENÇAS & ASSINATURAS", name:"STARLIX", lead:"", italic:"STARLIX", description:"Plataforma full stack para venda e gestão de licenças digitais, com checkout, assinaturas, área do cliente, revendedores, documentação e reset de hardware.", tags:["Next.js","Express","Supabase","TypeScript"], variant:"starlix", label:"VER REPOSITÓRIO", href:"https://github.com/AssisCabron/starlix" },
  { number:"06", kicker:"MARKETPLACE AUTOMOTIVO", name:"MOTORSTORE", lead:"", italic:"MOTORSTORE", description:"Marketplace de veículos com catálogo, busca por marca, autenticação e painel administrativo completo para gestão de veículos e usuários.", tags:["Laravel","MySQL","Blade","JavaScript"], variant:"motor", label:"VER REPOSITÓRIO", href:"https://github.com/AssisCabron/MotorStore" },
];

function ProjectVisual({ variant }: { variant: string }) {
  if (variant === "nexus") return <div className="project-visual nexus" aria-label="Interface conceitual do Nexus IA"><div className="mock-nav"><b>NEXUS / CONTROL ROOM</b><span>● ONLINE</span></div><div className="mock-grid"><div><small>PIPELINE</small><strong>12</strong><p>jobs ativos</p></div><div><small>PRODUÇÃO</small><strong>86%</strong><p>processado</p></div><div className="wide"><small>CONTEÚDO → MÍDIA → EDIÇÃO → PUBLICAÇÃO</small><div className="progress" /></div></div></div>;
  if (variant === "tragial") return <div className="project-visual tragial" aria-label="Interface conceitual do Tragial One"><div className="mock-nav"><b>TRAGIAL / ONE</b><span>TERÇA, 18 AGO</span></div><div className="clock">08<span>:</span>47</div><div className="time-row"><b>ENTRADA REGISTRADA</b><span>SEDE 01</span><span>AGORA</span></div><div className="sector-grid"><span>RH</span><span>COMERCIAL</span><span>LOGÍSTICA</span><span>FINANCEIRO</span></div></div>;
  if (variant === "vortex") return <div className="project-visual vortex" aria-label="Arquitetura conceitual do Vortex Platform"><div className="mock-nav"><b>VORTEX PLATFORM</b><span>RUNTIME / 03</span></div><div className="vortex-core"><span>EXPERIENCE</span><b>V</b><small>CORE RUNTIME</small></div><div className="node-line"><span>VELOCITY</span><span>MINES​TOM</span><span>LUA VM</span></div></div>;
  if (variant === "rex") return <div className="project-visual rex" aria-label="Painel conceitual do Rex Ecosystem"><div className="mock-nav"><b>REX / INFRASTRUCTURE</b><span>4 NODES</span></div><div className="server-list"><div><i>01</i><b>PRIMARY-NODE</b><span>78% CPU</span></div><div><i>02</i><b>GAME-RUNTIME</b><span>2.4 GB</span></div><div><i>03</i><b>EDGE-PROXY</b><span>ONLINE</span></div></div><div className="terminal">$ daemon status <b>all systems nominal_</b></div></div>;
  if (variant === "starlix") return <div className="project-visual starlix" aria-label="Interface conceitual do Starlix"><div className="mock-nav"><b>STARLIX</b><span>ACCOUNT / PRO</span></div><div className="license-card"><small>ACTIVE LICENSE</small><b>STARLIX / PRO</b><p>•••• •••• 9824</p><span>VALID UNTIL 2027</span></div><div className="license-meta"><span>SUBSCRIPTION ACTIVE</span><span>HWID CONNECTED</span></div></div>;
  return <div className="project-visual motor" aria-label="Interface conceitual do MotorStore"><div className="mock-nav"><b>MOTOR / STORE</b><span>CATÁLOGO 2026</span></div><div className="car-shape"><div className="roof"/><div className="body"/><i/><i/></div><div className="car-meta"><b>ENCONTRE O SEU PRÓXIMO CARRO.</b><span>CATÁLOGO / FILTROS / GESTÃO</span></div></div>;
}

export default function Home() {
  return <main id="top">
    <header className="topbar"><a className="brand" href="#top">ASSIS<span>®</span></a><p>FULL-STACK DEVELOPER / PRODUCT BUILDER</p><nav aria-label="Navegação principal"><a href="#projetos">projetos,</a><a href="#sobre"> sobre,</a><a href="#contato"> contato</a></nav></header>
    <section className="hero"><div className="hero-meta"><p>BRASIL — 2026</p><p>DISPONÍVEL PARA NOVOS PROJETOS</p></div><h1>EU TRANSFORMO<br/>IDEIAS COMPLEXAS<br/>EM PRODUTOS <em>REAIS.</em></h1><div className="hero-foot"><p>PLATAFORMAS, AUTOMAÇÕES<br/>E EXPERIÊNCIAS DIGITAIS.</p><div className="hero-note"><span>ESTRATÉGIA</span><span>DESIGN</span><span>CÓDIGO</span></div><a href="#projetos" aria-label="Ir para projetos">↓</a></div></section>
    <section className="manifesto" aria-label="Manifesto"><p>DO PRIMEIRO RASCUNHO AO</p><p><i>PRODUTO</i> EM PRODUÇÃO.</p></section>
    <section className="projects" id="projetos"><div className="section-title"><span>✦</span><h2>PROJETOS SELECIONADOS</h2><p>06 CASES / 2023—2026</p></div><div className="project-stack">{projects.map((project)=><article className="project-card" key={project.name}><div className="project-copy"><p className="index">{project.number} / {project.kicker}</p><h3>{project.lead}{project.lead && <br/>}<i>{project.italic}</i></h3><p className="description">{project.description}</p><div className="tags">{project.tags.map(tag=><span key={tag}>{tag}</span>)}</div>{project.href?<Link className="case-link" href={project.href} target="_blank" rel="noreferrer">{project.label} ↗</Link>:<p className="case-link private">{project.label} <span>●</span></p>}</div><ProjectVisual variant={project.variant}/></article>)}</div></section>
    <section className="archive" aria-label="Outros projetos"><p className="index">MAIS DO GITHUB</p><div className="archive-list"><Link href="https://github.com/AssisCabron/Indie-Community" target="_blank"><span>Indie Community</span><small>COMUNIDADE OPEN SOURCE</small><b>↗</b></Link><Link href="https://github.com/AssisCabron/Place-DB" target="_blank"><span>Place DB</span><small>DOCUMENTAÇÃO</small><b>↗</b></Link><Link href="https://github.com/AssisCabron/portfolio" target="_blank"><span>Portfolio v1</span><small>ARQUIVO / 2023</small><b>↗</b></Link></div></section>
    <section className="about" id="sobre"><div className="about-intro"><p className="index">SOBRE / ASSIS</p><h2>CONSTRUO O SISTEMA<br/>E PENSO NO <i>TODO.</i></h2></div><div className="about-grid"><p>Desenvolvedor full stack focado em transformar problemas operacionais e ideias ambiciosas em produtos digitais funcionais. Minha atuação atravessa produto, arquitetura, interface, automação e infraestrutura.</p><div className="skills"><p><span>01</span>PRODUTOS FULL STACK</p><p><span>02</span>AUTOMAÇÃO DE PROCESSOS</p><p><span>03</span>PLATAFORMAS COM IA</p><p><span>04</span>INFRAESTRUTURA & REAL-TIME</p></div></div><div className="tech-rail" aria-label="Tecnologias"><span>TYPESCRIPT</span><i>✦</i><span>NEXT.JS</span><i>✦</i><span>NODE.JS</span><i>✦</i><span>JAVA</span><i>✦</i><span>DOCKER</span><i>✦</i><span>MYSQL</span></div></section>
    <footer id="contato"><div className="footer-top"><p>VAMOS CONSTRUIR ALGO</p><span>↓</span></div><h2>FALE<br/>COMIGO<i>.</i></h2><div className="footer-links"><Link href="https://github.com/AssisCabron" target="_blank">GITHUB ↗</Link><Link href="https://github.com/AssisCabron?tab=repositories" target="_blank">REPOSITÓRIOS ↗</Link><a href="#top">VOLTAR AO TOPO ↑</a></div><div className="footer-base"><span>© 2026 ASSIS</span><span>DESENVOLVIDO COM INTENÇÃO.</span></div></footer>
  </main>;
}
